[package]
name = "libsmce-rs"
version = "0.1.0"
authors = ["Ruthger Dijt <ruthgerdijt@gmail.com>"]
edition = "2018"
links = "SMCE"

[dependencies]
cxx = { version = "1.0", features = ["c++20"] }

[build-dependencies]
cxx-build = "1.0"
