name: Build & Test

on: [push, pull_request]

jobs:
  Linux:
    name: Ubuntu Build & Test
    runs-on: ubuntu-latest
    env:
      CC: gcc-10
      CXX: g++-10
    steps:
      - name: Deps
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install ninja-build
          brew install arduino-cli
          wget -O libsmce.sh https://github.com/ItJustWorksTM/libSMCE/releases/download/v1.2.4/libSMCE-1.2.4-Linux-x86_64-GNU.sh
          chmod +x libsmce.sh
          sudo ./libsmce.sh --prefix=/usr --skip-license --exclude-subdir
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --nocapture

  MacOS:
    name: MacOS Build & Test
    runs-on: macos-latest
    env:
      CC: clang
      CXX: clang++
      CXXFLAGS: -std=c++2a

    steps:
      - name: Deps
        run: |
          brew install ninja arduino-cli
          echo $LIBSMCE_BASE_URL/libSMCE-$LIBSMCE_VERSION-Linux-x86_64-Clang.sh
          wget -O libsmce.sh https://github.com/ItJustWorksTM/libSMCE/releases/download/v1.2.4/libSMCE-1.2.4-Darwin-x86_64-AppleClang.sh
          chmod +x libsmce.sh
          sudo ./libsmce.sh --prefix=/usr/local --skip-license --exclude-subdir
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --nocapture

#  Windows:
#    name: Windows Build & Test
#    runs-on: windows-latest
#    env:
#      SMCE_ROOT: C:\smce
#      SMCE_DIR: C:\smce\lib\cmake\SMCE
#      CMAKE_PREFIX_PATH: C:\smce
#    steps:
#      - name: Deps
#        run: |
#          choco install wget ninja arduino-cli openssl > silence
#          wget -O libsmce.zip https://github.com/ItJustWorksTM/libSMCE/releases/download/v1.2.4/libSMCE-1.2.4-Windows-AMD64-MSVC-Release.zip
#          7z x libsmce.zip -oC:\
#          ren C:\libSMCE-1.2.4-Windows-AMD64-MSVC-Release C:\smce
#          dir C:\smce
#          echo %SMCE_ROOT%
#      - uses: ilammy/msvc-dev-cmd@v1
#      - uses: actions/checkout@v2
#      - uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#          override: true
#      - uses: Swatinem/rust-cache@v1
#      - name: Build
#        uses: actions-rs/cargo@v1
#        with:
#          command: build
#          args: --all-targets
#      - name: Test
#        uses: actions-rs/cargo@v1
#        with:
#          command: test
#          args: -- --nocapture
