name: Build & Test

on: [push, pull_request]

env:
  LIBSMCE_BASE_URL: https://github.com/ItJustWorksTM/libSMCE/releases/download/v1.2.4
  LIBSMCE_VERSION: 1.2.4

jobs:
  Linux:
    name: Linux Test
    runs-on: ubuntu-latest
    env:
      CC: gcc-10
      CXX: g++-10
    steps:
      - name: Deps
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install ninja-build
          ninja --version # technically not a dependency, but used to speedup builds
          cmake --version
          brew install arduino-cli
          arduino-cli version
          echo $LIBSMCE_BASE_URL/libSMCE-$LIBSMCE_VERSION-Linux-x86_64-Clang.sh
          wget --output-document libsmce.sh $LIBSMCE_BASE_URL/libSMCE-$LIBSMCE_VERSION-Linux-x86_64-GNU.sh
          chmod +x libsmce.sh
          sudo ./libsmce.sh --prefix=/usr --skip-license --exclude-subdir
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - name: Builduild
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets
      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --nocapture
